version: "4"
services:
  nginx:
    depends_on:
      - back-end
      - front-end
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
  back-end:
    build:
      dockerfile: Dockerfile.dev
      context: "./back-end"
    volumes:
      - /app/node_modules
      - ./back-end:/app
  front-end:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile.dev
      context: ./front-end
    volumes:
      - /app/node_modules
      - ./front-end:/app
